openapi: 3.0.0
info:
  title: Menu
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /Menu/NewGame:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: |-
            OK
            GameToken - ключ, по которому можно присоединиться к игре
          content:
            application/json:
              schema:
                type: object
                properties:
                  GameKey:
                    type: string
              examples: {}
        '401':
          description: Unauthorized
        '409':
          description: |-
            Conflict
            Если игрок уже находится в сессии
      operationId: get-Menu-NewGame
      parameters:
        - schema:
            type: string
          in: header
          name: Autorization
          description: 'Bearer {token}'
  /Menu/JoinGame:
    post:
      summary: ''
      operationId: post-Menu-JoinGame
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: |-
            Forbidden
            Если комната полная
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                GameKey:
                  type: string
        description: 'GameKey - ключ игры, к которому нужно присоединиться'
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer {token}'
  /Menu/LeaveGame:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '409':
          description: |-
            Conflict
            Если не находится в игре
      operationId: get-Menu-LeaveGame
components:
  schemas: {}
