include:
  - project: "the-coolest-developers/devops/shared-pilelines"
    ref: v1.0.8 
    file: "shared.yml"

variables:
  SOLUTION_PATH: "${CI_PROJECT_DIR}/Source/${PROJECT_NAME}.sln"

stages:
  - build_code_base
  - code_scan

build_source_code:
  stage: build_code_base
  extends: .build
